<?php
$arrWords = [
'7/24 Acil Hizmet',
'Arayın, Hemen Geliriz!',
'#1. Kalite Hizmet',
'%25 İndirim',
'%100 Müşteri Memnuniyeti',
'1 Yıl Garanti',
'30 Dakika Servis Süresi',
'En Yakın Servis',
'%100 Güvenilir',
'En Ucuz Hizmet',
'Hızlı, Hesaplı, Kaliteli Hizmet',
'Bizi Hemen Arayın',
'Hemen Teklif Al',
'Profesyonel Hizmet',
'Size En Yakın Hizmet',
'Hemen Telefon Et',
'%100 Memnuniyet',
'7/24 Arayın!',
'Ucuza Hizmet Al',
'Garantili Hizmet Al',
'En İyi Hizmeti Al',
'Kaliteli Hizmet Al',
'Hemen Servis Çağır',
'En Uygun Fiyatlar',
'Yüzlerce Mutlu Müşteri',
'İşinin Ehli Firma',
'Güvenilir Firma',
'Uzman Ekip',
'Güleryüzlü Hizmet',
'Hijyen Kurallarına Uygun',
'Anında Çözüm',
'7/24 En Yakın Servis',
'Kaliteli ve Garantili',
'#1. Kalite İşçilik',
'Kesin Çözüm',
'Tıkla, Hemen Ara',
'İşinin En İyisi #1.'
];